name: Upload Python Package gnssmultipath to PYPI without version increment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel build twine

      - name: Build and upload to PyPI
        run: |
          python -m build
          twine upload --password ${{ secrets.PYPI_TOKEN }} dist/*
